-- BiteMap seed data, generated from seed/*.csv (research record collected 30/08/2026).
-- Loads into the schema of BACKEND_REQUIREMENTS.md §5 in FK order:
--   creators -> platform_accounts -> places -> posts.
-- Applied automatically by `supabase db reset` (config.toml [db.seed] sql_paths = ["./seed.sql"]).
-- All places are seeded as status 'published' with hand-assigned lat/lng
-- inside the KL metro bounding box (real coordinates for well-known areas,
-- area-centroid + small unique jitter otherwise) so nearby_places has data
-- to return in dev. The places insert upserts on id (on conflict do update
-- lat/lng/status) so this file stays idempotent across reseeds.
-- No rows for users/user_ratings: Supabase Auth and the app own those at runtime.

begin;

insert into public.creators
  (id, display_name, bio, avatar_url, avatar_source_url, avatar_fetched_at,
   niche_tags, maps_list_url, content_type, is_operator, is_active, notes)
values
  ('mingchuun', 'Ming Chun', NULL, NULL, NULL, NULL, array['ayam-gepuk', 'kl-eats']::text[], NULL, 'venue_reviewer'::creator_content_type, true, true, 'OPERATOR. Owns Gepuklah. 0 of 6 sampled posts were third-party recommendations - all six were his own venue. Do not seed venues from this account without an independent second source.'),
  ('tomato-ate-it', 'Tomato', NULL, NULL, NULL, NULL, array['reviews', 'cafes', 'japanese']::text[], NULL, 'venue_reviewer'::creator_content_type, false, true, 'Bio says ''honest reviews only'' but 7 of 11 sampled posts were brand deals or personal. Her 2024 posts are the richest in the set - full addresses, per-item ratings, prices. Format drifted toward sponsored over time.'),
  ('jajabinxz', 'Jared', NULL, NULL, NULL, NULL, array['budget-eats', 'hawker', 'value']::text[], NULL, 'venue_reviewer'::creator_content_type, false, true, '8 of 11 sampled posts were genuine venue visits. Consistent caption template ''{VENUE} @ {AREA}''. States prices and is willing to call things overpriced.'),
  ('nomnomswithta', 'Ta', NULL, NULL, NULL, NULL, array['cafes', 'casual', 'klang-valley']::text[], NULL, 'venue_reviewer'::creator_content_type, false, true, 'BEST YIELD IN SAMPLE: 10 of 10 sampled posts were genuine venue visits, every one location-tagged. Rigid template ''Today I am eating with my mouth closed at [pin]{VENUE}, {AREA}''. Gives honest mixed verdicts, not just praise.'),
  ('jcinthehizzay', 'Jason Chen', NULL, NULL, NULL, NULL, array['shiopan', 'desserts', 'shah-alam']::text[], NULL, 'venue_reviewer'::creator_content_type, false, true, '5 of 7 sampled posts were venue visits, but he rarely uses location tags - venue identity sits in hashtags (#koppiku, #gentlemess, #cakejalantiung). Also covers pop-ups and food fests, which are not permanent venues.');

insert into public.platform_accounts
  (id, creator_id, platform, handle, external_id, follower_count, profile_url)
values
  ('pa-mingchuun', 'mingchuun', 'instagram'::platform_kind, 'mingchuun', NULL, 127000, 'https://www.instagram.com/mingchuun/'),
  ('pa-tomato-ate-it', 'tomato-ate-it', 'instagram'::platform_kind, 'tomato_ate_it', NULL, 50900, 'https://www.instagram.com/tomato_ate_it/'),
  ('pa-jajabinxz', 'jajabinxz', 'instagram'::platform_kind, 'jajabinxz', NULL, 24400, 'https://www.instagram.com/jajabinxz/'),
  ('pa-nomnomswithta', 'nomnomswithta', 'instagram'::platform_kind, 'nomnomswithta', NULL, 25700, 'https://www.instagram.com/nomnomswithta/'),
  ('pa-jcinthehizzay', 'jcinthehizzay', 'instagram'::platform_kind, 'jcinthehizzay', NULL, 164000, 'https://www.instagram.com/jcinthehizzay/');

insert into public.places
  (id, provider_place_id, name, name_aliases, lat, lng, address, area, category,
   halal_status, price_band, hours_note, operational_status,
   photo_url, photo_source, photo_source_url, photo_credit, photo_fetched_at,
   photo_visible, status, notes)
values
  ('two-fold-coffee', NULL, 'Two Fold Coffee', 3.109, 101.6021, NULL, NULL, 'Kelana Jaya', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Shio pan; eat hot. Repeat visitor, near home.'),
  ('since-then', NULL, 'Since Then', 3.1275, 101.6803, NULL, NULL, 'Bangsar', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Tom yum is the must-order. Comfort repeat.'),
  ('gepuklah-by-mingchuun', NULL, 'Gepuklah By Mingchuun', array['Gepuklah']::text[], 3.1368, 101.6194, NULL, 'Damansara Jaya', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'INDEPENDENT source for Gepuklah. Mixed verdict: worth trying, not worth the queue.'),
  ('don-t-tell-mama', NULL, 'Don''t Tell Mama', 3.1405, 101.6852, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Parking and queue are a headache. Pet-friendly outdoor.'),
  ('sisters-place', NULL, 'Sisters Place', 3.1465, 101.6303, NULL, NULL, 'TTDI', NULL,
   'unknown'::halal_status, 'rm10_25'::price_band, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Muslim Friendly CKT RM20; squid prawn kerang. Halal wording is the creator''s, NOT verified. price_band from stated CKT RM20.'),
  ('niji-izakaya', NULL, 'Niji Izakaya', 3.1481, 101.713, NULL, NULL, 'KL', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Opened a few months ago. Venue has its own IG account.'),
  ('koppiku', NULL, 'Koppiku', 3.1195, 101.6551, NULL, NULL, 'Universiti Malaya', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'HARD CASE: venue identity only in #koppiku #universitimalaya. No tag, no caption name.'),
  ('a-rest', NULL, 'A''rest', 3.1414, 101.7195, NULL, NULL, 'TRX', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Underwhelming vs expectations but would return to work/chill. Honest negative-ish.'),
  ('555-thainanese-chicken-rice', NULL, '555 Thainanese Chicken Rice', 3.1673, 101.6534, NULL, NULL, 'Sri Hartamas', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Decent cozy family chicken rice. Venue has IG @555thainanese.'),
  ('gentle-mess', NULL, 'Gentle Mess', 3.142, 101.69, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'HARD CASE 2: venue only in #gentlemess #cafegentlemess. Same pattern as Koppiku.'),
  ('fujisawa-izakaya', NULL, 'Fujisawa Izakaya', 3.174, 101.6521, NULL, NULL, 'Steppes Mont Kiara', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Few options at Steppes. Lazy caption but venue fully specified.'),
  ('nale-the-nasi-lemak-company', NULL, 'Nale The Nasi Lemak Company', 3.1497, 101.609, NULL, NULL, 'Damansara Pavilion', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'RM289 indomie platter - creator calls it very pricey. NEGATIVE-ish. price_band left null: RM289 is a sharing platter; per-person spend unknown.'),
  ('serdang-midnight-curry-mee-stall', NULL, 'Serdang Midnight Curry Mee Stall', 3.0035, 101.7083, NULL, NULL, 'Kampung Baru Seri Kembangan', NULL,
   'unknown'::halal_status, NULL, 'Open till ~3am (creator-reported)', 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'STALL. Open till 3am - hours_note. Roadside parking. YTF RM2-2.50/pc. RM69 pricey but yumz.'),
  ('golden-city-seafood-restaurant-kopitiam', NULL, 'Golden City Seafood Restaurant Kopitiam', 3.1963, 101.6473, NULL, NULL, 'Taman Sri Segambut', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'CAPTION USELESS - ''We did not finish the whole thing''. Venue comes 100% from the location tag. Wantan mee.'),
  ('unnamed-kelapa-laut-stall', NULL, 'UNNAMED kelapa laut stall', 3.0744, 101.5535, NULL, NULL, 'Seksyen 7 Shah Alam', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'HARD: tag is a RELATIVE DESCRIPTION not a venue name. Unnamed street stall. Shah Alam - outside SPEC 5 areas.'),
  ('deewow', NULL, 'DEEWOW', 3.2135, 101.6353, NULL, NULL, 'Kepong', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Thai food. Celebrity-owned - ''could''ve used just his face and fame''. Would revisit.'),
  ('lai-foong-lala-noodle', NULL, 'Lai Foong Lala Noodle', 3.1435, 101.6885, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Creator calls it one of the best lala noodle in Malaysia. STRONG positive.'),
  ('kbb-steak', NULL, 'KBB Steak', 3.1491, 101.6276, NULL, NULL, 'TTDI', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Wild Ribs Burger. Short strong positive.'),
  ('ibrahim-pisang-cheese-banjir', NULL, 'Ibrahim Pisang Cheese Banjir', 3.0063, 101.7788, NULL, NULL, 'Bangi', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'OUT OF SPEC AREA - Bangi not in the 5 KV areas. Pisang cheese banjir.'),
  ('cake-jalan-tiung', NULL, 'Cake Jalan Tiung', 3.145, 101.6918, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'HARD CASE 3: venue only in #cakejalantiung. Butter tteok + shiopan. Pattern is consistent for this creator.'),
  ('makhan-by-kitchen-mafia', NULL, 'Makhan By Kitchen Mafia', 3.1059, 101.6053, NULL, NULL, 'PJ', NULL,
   'non_halal'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'BOTH venue post AND sponsored (Guinness collab). Real visit, real verdict ''pleasant surprise, can try''. Non-halal - serves alcohol. halal_status = non_halal from the venue''s own Guinness collab, not a creator claim.'),
  ('hikiniku-to-come', NULL, 'Hikiniku to Come', 3.1465, 101.6935, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, 'rm50_plus'::price_band, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'RM67.90++ set. Opening 15 Aug. ''restaurant is LEGIT''. Venue has own IG. price_band from stated RM67.90++ set price.'),
  ('klcg-confectionery-bakery', NULL, 'KLCG Confectionery Bakery', 3.1649, 101.7273, NULL, NULL, 'Kampung Datuk Keramat', NULL,
   'unknown'::halal_status, 'rm10_25'::price_band, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'RICHEST RECORD. Full address in caption. [MUSLIM FRIENDLY] marker. Per-item ratings+prices: Pistachio Supreme 8/10 RM15.90, Strawberry&Creme 7/10 RM15.90, Pain Suisse Hazelnut Praline 10/10 RM16.90. price_band from stated per-item prices. Halal wording is the creator''s, NOT verified.'),
  ('chilli-s', NULL, 'Chilli''s', 3.1086, 101.6334, NULL, NULL, 'Jaya Shopping Centre PJ', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'Fried mozzarella 3pc RM33.60. Chain venue in a mall. price_band left null: only an appetizer price is stated.'),
  ('meat-heaven-kl', NULL, 'Meat Heaven KL', 3.148, 101.695, NULL, NULL, NULL, NULL,
   'unknown'::halal_status, 'rm50_plus'::price_band, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'PURE C2 CASE: no location tag, no venue name in caption. Resolved 100% by @-mention. A5 Miyazaki Wagyu Donburi RM299 promo 400-450g. price_band from stated RM299 donburi.'),
  ('sweets-by-baby-pop-up-stall', NULL, 'Sweets by Baby (pop-up stall)', 3.0715, 101.5548, NULL, NULL, 'Dataran Karnival Shah Alam', NULL,
   'unknown'::halal_status, NULL, NULL, 'unknown'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'POP-UP at a food fest, not a permanent venue. Creator warns similar names exist and to waze ''perkarangan stadium shah alam'' - he hit the wrong place 3 times himself. operational_status unknown: the fest has ended.'),
  ('unnamed-claypot-rice-raw-crab-2-outlets', NULL, 'UNNAMED claypot rice / raw crab (2 outlets)', 3.0581, 101.5865, NULL, NULL, 'Subang Jaya + Kepong', NULL,
   'unknown'::halal_status, NULL, NULL, 'operational'::operational_status,
   NULL, NULL, NULL, NULL, NULL, true, 'published'::place_status, 'MULTI-OUTLET: one post, two addresses. Venue name never given. ''(No Pork No Alcohol)'' = pork_free signal, creator''s words only - so halal_status stays unknown.')
on conflict (id) do update set
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status;

-- posts: the CSV's resolved_by / location_tag_kind research columns are not part
-- of §5 and are deliberately not loaded.
insert into public.posts
  (id, creator_id, platform_account_id, place_id, platform, post_url, thumbnail_url,
   media_kind, content_summary, is_sponsored, is_self_interest, posted_at,
   ingest_status, excluded_reason)
values
  ('post-DcgGW1BPP9j', 'nomnomswithta', 'pa-nomnomswithta', 'two-fold-coffee', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcgGW1BPP9j/', NULL,
   'post'::post_media_kind, 'Shio pan; eat hot. Repeat visitor, near home.', false, false, timestamptz '2026-08-26', 'matched'::post_ingest_status, NULL),
  ('post-DcL64_sz_Wg', 'nomnomswithta', 'pa-nomnomswithta', 'since-then', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcL64_sz_Wg/', NULL,
   'post'::post_media_kind, 'Tom yum is the must-order. Comfort repeat.', false, false, timestamptz '2026-08-18', 'matched'::post_ingest_status, NULL),
  ('post-DcBF0CLTQPH', 'nomnomswithta', 'pa-nomnomswithta', 'gepuklah-by-mingchuun', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcBF0CLTQPH/', NULL,
   'post'::post_media_kind, 'INDEPENDENT source for Gepuklah. Mixed verdict: worth trying, not worth the queue.', false, false, timestamptz '2026-08-14', 'matched'::post_ingest_status, NULL),
  ('post-Db5XwxlTvgo', 'nomnomswithta', 'pa-nomnomswithta', 'don-t-tell-mama', 'instagram'::platform_kind, 'https://www.instagram.com/p/Db5XwxlTvgo/', NULL,
   'post'::post_media_kind, 'Parking and queue are a headache. Pet-friendly outdoor.', false, false, timestamptz '2026-08-11', 'matched'::post_ingest_status, NULL),
  ('post-Dcije7Xh5Mm', 'jajabinxz', 'pa-jajabinxz', 'sisters-place', 'instagram'::platform_kind, 'https://www.instagram.com/p/Dcije7Xh5Mm/', NULL,
   'post'::post_media_kind, 'Muslim Friendly CKT RM20; squid prawn kerang. Halal wording is the creator''s, NOT verified.', false, false, timestamptz '2026-08-27', 'matched'::post_ingest_status, NULL),
  ('post-DcitrelSX4L', 'tomato-ate-it', 'pa-tomato-ate-it', 'niji-izakaya', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcitrelSX4L/', NULL,
   'post'::post_media_kind, 'Opened a few months ago. Venue has its own IG account.', false, false, timestamptz '2026-08-27', 'matched'::post_ingest_status, NULL),
  ('post-DcalZwLyOYw', 'jcinthehizzay', 'pa-jcinthehizzay', 'koppiku', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcalZwLyOYw/', NULL,
   'post'::post_media_kind, 'HARD CASE: venue identity only in #koppiku #universitimalaya. No tag, no caption name.', false, false, timestamptz '2026-08-24', 'matched'::post_ingest_status, NULL),
  ('post-DcituqLhD9x', 'jajabinxz', 'pa-jajabinxz', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcituqLhD9x/', NULL,
   'post'::post_media_kind, 'Shihlin brand promo; RM690 competition. #Shihlin', true, false, timestamptz '2026-08-27', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-Dbxaw86h2yw', 'jajabinxz', 'pa-jajabinxz', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/Dbxaw86h2yw/', NULL,
   'post'::post_media_kind, 'Mi Sedaap instant noodle product ad.', true, false, timestamptz '2026-08-08', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-DcTLkZpJni1', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcTLkZpJni1/', NULL,
   'post'::post_media_kind, 'Joining her brothers'' startup. Not food.', false, false, timestamptz '2026-08-21', 'excluded'::post_ingest_status, 'personal'),
  ('post-DcQmvVsJH5q', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcQmvVsJH5q/', NULL,
   'post'::post_media_kind, 'Shanghai restaurant list + Mastercard/Alipay promo. Outside Klang Valley.', true, false, timestamptz '2026-08-20', 'excluded'::post_ingest_status, 'out_of_scope+sponsored'),
  ('post-DcQUzl6HTxG', 'jcinthehizzay', 'pa-jcinthehizzay', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcQUzl6HTxG/', NULL,
   'post'::post_media_kind, 'Shiopan ranking list but wrapped in a Ryt Bank angpao promo.', true, false, timestamptz '2026-08-20', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-DcVxMOsRCeh', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcVxMOsRCeh/', NULL,
   'post'::post_media_kind, 'Seat-count business reasoning for his own venues.', false, true, timestamptz '2026-08-22', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-DcQtvIDhGTM', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcQtvIDhGTM/', NULL,
   'post'::post_media_kind, 'Gepuklah Friends Month promo. Names 3 partner venues as promo, not recommendation.', false, true, timestamptz '2026-08-20', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-DbLL9KxPC9a', 'nomnomswithta', 'pa-nomnomswithta', 'a-rest', 'instagram'::platform_kind, 'https://www.instagram.com/p/DbLL9KxPC9a/', NULL,
   'post'::post_media_kind, 'Underwhelming vs expectations but would return to work/chill. Honest negative-ish.', false, false, timestamptz '2026-07-24', 'matched'::post_ingest_status, NULL),
  ('post-Dah2dEUvCPm', 'nomnomswithta', 'pa-nomnomswithta', '555-thainanese-chicken-rice', 'instagram'::platform_kind, 'https://www.instagram.com/p/Dah2dEUvCPm/', NULL,
   'post'::post_media_kind, 'Decent cozy family chicken rice. Venue has IG @555thainanese.', false, false, timestamptz '2026-07-08', 'matched'::post_ingest_status, NULL),
  ('post-DcNwwhGNbfi', 'jcinthehizzay', 'pa-jcinthehizzay', 'gentle-mess', 'instagram'::platform_kind, 'https://www.instagram.com/p/DcNwwhGNbfi/', NULL,
   'post'::post_media_kind, 'HARD CASE 2: venue only in #gentlemess #cafegentlemess. Same pattern as Koppiku.', false, false, timestamptz '2026-08-19', 'matched'::post_ingest_status, NULL),
  ('post-DbF8DBFxCMC', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DbF8DBFxCMC/', NULL,
   'post'::post_media_kind, 'Gepuklah opening countdown, 10 days out.', false, true, timestamptz '2026-07-22', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-DcTaDCKn6Uz', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcTaDCKn6Uz/', NULL,
   'post'::post_media_kind, 'Day in the life of his own shop. Sold out flex.', false, true, timestamptz '2026-08-21', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-DaU6d2ePsJh', 'nomnomswithta', 'pa-nomnomswithta', 'fujisawa-izakaya', 'instagram'::platform_kind, 'https://www.instagram.com/p/DaU6d2ePsJh/', NULL,
   'post'::post_media_kind, 'Few options at Steppes. Lazy caption but venue fully specified.', false, false, timestamptz '2026-07-03', 'matched'::post_ingest_status, NULL),
  ('post-DR7sW4Pkwl4', 'jajabinxz', 'pa-jajabinxz', 'nale-the-nasi-lemak-company', 'instagram'::platform_kind, 'https://www.instagram.com/p/DR7sW4Pkwl4/', NULL,
   'post'::post_media_kind, 'RM289 indomie platter - creator calls it very pricey. NEGATIVE-ish.', false, false, timestamptz '2025-12-06', 'matched'::post_ingest_status, NULL),
  ('post-DbbBdyrBWz-', 'jajabinxz', 'pa-jajabinxz', 'serdang-midnight-curry-mee-stall', 'instagram'::platform_kind, 'https://www.instagram.com/p/DbbBdyrBWz-/', NULL,
   'post'::post_media_kind, 'STALL. Open till 3am - hours_note. Roadside parking. YTF RM2-2.50/pc. RM69 pricey but yumz.', false, false, timestamptz '2026-07-30', 'matched'::post_ingest_status, NULL),
  ('post-DcLdKZdJPtO', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcLdKZdJPtO/', NULL,
   'post'::post_media_kind, 'KFC #CaraOriKFC contest. Home recipe, not a venue.', true, false, timestamptz '2026-08-18', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-DcI4WY6pYU5', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcI4WY6pYU5/', NULL,
   'post'::post_media_kind, 'Knorr Pasti Sedap seasoning. Home cooking.', true, false, timestamptz '2026-08-17', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-Da-TdbFB0Mk', 'jajabinxz', 'pa-jajabinxz', 'golden-city-seafood-restaurant-kopitiam', 'instagram'::platform_kind, 'https://www.instagram.com/p/Da-TdbFB0Mk/', NULL,
   'post'::post_media_kind, 'CAPTION USELESS - ''We did not finish the whole thing''. Venue comes 100% from the location tag. Wantan mee.', false, false, timestamptz '2026-07-19', 'matched'::post_ingest_status, NULL),
  ('post-Db2iOl0yz-d', 'jcinthehizzay', 'pa-jcinthehizzay', 'unnamed-kelapa-laut-stall', 'instagram'::platform_kind, 'https://www.instagram.com/p/Db2iOl0yz-d/', NULL,
   'post'::post_media_kind, 'HARD: tag is a RELATIVE DESCRIPTION not a venue name. Unnamed street stall. Shah Alam - outside SPEC 5 areas.', false, false, timestamptz '2026-08-10', 'matched'::post_ingest_status, NULL),
  ('post-DbYI_SXB5rq', 'jajabinxz', 'pa-jajabinxz', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DbYI_SXB5rq/', NULL,
   'post'::post_media_kind, 'KFC brand post. Same campaign wave as tomato_ate_it DcLdKZdJPtO.', true, false, timestamptz '2026-07-29', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-DcEQiXRpwLJ', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcEQiXRpwLJ/', NULL,
   'post'::post_media_kind, 'Sabah travel reel. Two emoji caption.', false, false, timestamptz '2026-08-15', 'excluded'::post_ingest_status, 'out_of_scope'),
  ('post-DZxb_0kT8p-', 'nomnomswithta', 'pa-nomnomswithta', 'deewow', 'instagram'::platform_kind, 'https://www.instagram.com/p/DZxb_0kT8p-/', NULL,
   'post'::post_media_kind, 'Thai food. Celebrity-owned - ''could''ve used just his face and fame''. Would revisit.', false, false, timestamptz '2026-06-19', 'matched'::post_ingest_status, NULL),
  ('post-DZpRvwfT1wc', 'nomnomswithta', 'pa-nomnomswithta', 'lai-foong-lala-noodle', 'instagram'::platform_kind, 'https://www.instagram.com/p/DZpRvwfT1wc/', NULL,
   'post'::post_media_kind, 'Creator calls it one of the best lala noodle in Malaysia. STRONG positive.', false, false, timestamptz '2026-06-16', 'matched'::post_ingest_status, NULL),
  ('post-DZkMwOkhr4A', 'jajabinxz', 'pa-jajabinxz', 'kbb-steak', 'instagram'::platform_kind, 'https://www.instagram.com/p/DZkMwOkhr4A/', NULL,
   'post'::post_media_kind, 'Wild Ribs Burger. Short strong positive.', false, false, timestamptz '2026-06-14', 'matched'::post_ingest_status, NULL),
  ('post-DZ9tqDShgvX', 'jajabinxz', 'pa-jajabinxz', 'ibrahim-pisang-cheese-banjir', 'instagram'::platform_kind, 'https://www.instagram.com/p/DZ9tqDShgvX/', NULL,
   'post'::post_media_kind, 'OUT OF SPEC AREA - Bangi not in the 5 KV areas. Pisang cheese banjir.', false, false, timestamptz '2026-06-24', 'matched'::post_ingest_status, NULL),
  ('post-DbsLyErN89G', 'jcinthehizzay', 'pa-jcinthehizzay', 'cake-jalan-tiung', 'instagram'::platform_kind, 'https://www.instagram.com/p/DbsLyErN89G/', NULL,
   'post'::post_media_kind, 'HARD CASE 3: venue only in #cakejalantiung. Butter tteok + shiopan. Pattern is consistent for this creator.', false, false, timestamptz '2026-08-06', 'matched'::post_ingest_status, NULL),
  ('post-DcD8ZfzEV5y', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DcD8ZfzEV5y/', NULL,
   'post'::post_media_kind, 'Bought a car. Contains a third-party phone number - NOT stored per PDPA.', false, false, timestamptz '2026-08-15', 'excluded'::post_ingest_status, 'personal'),
  ('post-DZgbHQCz3XT', 'nomnomswithta', 'pa-nomnomswithta', 'makhan-by-kitchen-mafia', 'instagram'::platform_kind, 'https://www.instagram.com/p/DZgbHQCz3XT/', NULL,
   'post'::post_media_kind, 'BOTH venue post AND sponsored (Guinness collab). Real visit, real verdict ''pleasant surprise, can try''. Non-halal - serves alcohol.', true, false, timestamptz '2026-06-12', 'matched'::post_ingest_status, NULL),
  ('post-Db8AcNspred', 'tomato-ate-it', 'pa-tomato-ate-it', 'hikiniku-to-come', 'instagram'::platform_kind, 'https://www.instagram.com/p/Db8AcNspred/', NULL,
   'post'::post_media_kind, 'RM67.90++ set. Opening 15 Aug. ''restaurant is LEGIT''. Venue has own IG.', false, false, timestamptz '2026-08-12', 'matched'::post_ingest_status, NULL),
  ('post-Db7CpvqyWin', 'jcinthehizzay', 'pa-jcinthehizzay', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/Db7CpvqyWin/', NULL,
   'post'::post_media_kind, 'DJI Osmo 360 camera ad. Roller coaster. Not food at all.', true, false, timestamptz '2026-08-11', 'excluded'::post_ingest_status, 'sponsored'),
  ('post-DCGmwv-pjuF', 'tomato-ate-it', 'pa-tomato-ate-it', 'klcg-confectionery-bakery', 'instagram'::platform_kind, 'https://www.instagram.com/p/DCGmwv-pjuF/', NULL,
   'post'::post_media_kind, 'RICHEST RECORD. Full address in caption. [MUSLIM FRIENDLY] marker. Per-item ratings+prices: Pistachio Supreme 8/10 RM15.90, Strawberry&Creme 7/10 RM15.90, Pain Suisse Hazelnut Praline 10/10 RM16.90. Overall 9/10. Long queue but good system, designated parking with guides.', false, false, timestamptz '2024-11-08', 'matched'::post_ingest_status, NULL),
  ('post-DMlcZFxTwnR', 'jajabinxz', 'pa-jajabinxz', 'chilli-s', 'instagram'::platform_kind, 'https://www.instagram.com/p/DMlcZFxTwnR/', NULL,
   'post'::post_media_kind, 'Fried mozzarella 3pc RM33.60. Chain venue in a mall.', false, false, timestamptz '2025-07-26', 'matched'::post_ingest_status, NULL),
  ('post-DGFvN1KJOMg', 'tomato-ate-it', 'pa-tomato-ate-it', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/DGFvN1KJOMg/', NULL,
   'post'::post_media_kind, 'Farmstay/staycation, not a makan venue. Tag and mention both clean though.', false, false, timestamptz '2025-02-15', 'excluded'::post_ingest_status, 'not_a_restaurant'),
  ('post-Db_BqllH6qZ', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/Db_BqllH6qZ/', NULL,
   'post'::post_media_kind, '''we are open tomorrow!!!'' - his own shop.', false, true, timestamptz '2026-08-13', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-Db-tKyKNZtM', 'mingchuun', 'pa-mingchuun', NULL, 'instagram'::platform_kind, 'https://www.instagram.com/p/Db-tKyKNZtM/', NULL,
   'post'::post_media_kind, 'Gepuklah 5th Update + Eclipse gum partnership. Self-interest AND sponsored.', true, true, timestamptz '2026-08-13', 'excluded'::post_ingest_status, 'self_interest'),
  ('post-DBtDrv3p3qv', 'tomato-ate-it', 'pa-tomato-ate-it', 'meat-heaven-kl', 'instagram'::platform_kind, 'https://www.instagram.com/p/DBtDrv3p3qv/', NULL,
   'post'::post_media_kind, 'PURE C2 CASE: no location tag, no venue name in caption. Resolved 100% by @-mention. A5 Miyazaki Wagyu Donburi RM299 promo 400-450g.', false, false, timestamptz '2024-10-29', 'matched'::post_ingest_status, NULL),
  ('post-DckPSrwSWNx', 'jcinthehizzay', 'pa-jcinthehizzay', 'sweets-by-baby-pop-up-stall', 'instagram'::platform_kind, 'https://www.instagram.com/p/DckPSrwSWNx/', NULL,
   'post'::post_media_kind, 'POP-UP at a food fest, not a permanent venue. Creator warns similar names exist and to waze ''perkarangan stadium shah alam'' - he hit the wrong place 3 times himself.', false, false, timestamptz '2026-08-27', 'matched'::post_ingest_status, NULL),
  ('post-DQqz0_ggVMs', 'jajabinxz', 'pa-jajabinxz', 'unnamed-claypot-rice-raw-crab-2-outlets', 'instagram'::platform_kind, 'https://www.instagram.com/p/DQqz0_ggVMs/', NULL,
   'post'::post_media_kind, 'MULTI-OUTLET: one post, two addresses. Venue name never given. ''(No Pork No Alcohol)'' = pork_free signal, creator''s words only.', false, false, timestamptz '2025-11-05', 'matched'::post_ingest_status, NULL);

commit;
