import type { Config } from "tailwindcss";

// Design tokens ported from /design.md (frontmatter) and the legacy
// frontend/js/head.html inline `tailwind.config` (Play CDN config, now
// replaced by this built config). Token names are kept identical so
// existing markup classes (bg-map-background, text-sheet-on-surface, ...)
// port over unchanged.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fff8f6",
        "surface-dim": "#efd5ca",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1eb",
        "surface-container": "#ffeae1",
        "surface-container-high": "#fee3d8",
        "surface-container-highest": "#f8ddd2",
        "on-surface": "#261812",
        "on-surface-variant": "#5a4136",
        "inverse-surface": "#3d2d26",
        "inverse-on-surface": "#ffede6",
        outline: "#8e7164",
        "outline-variant": "#e2bfb0",
        "surface-tint": "#a04100",
        primary: "#a04100",
        "on-primary": "#ffffff",
        "primary-container": "#ff6b00",
        "on-primary-container": "#572000",
        "inverse-primary": "#ffb693",
        secondary: "#006d43",
        "on-secondary": "#ffffff",
        "secondary-container": "#99f2bd",
        "on-secondary-container": "#0a7147",
        tertiary: "#0062a1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#059eff",
        "on-tertiary-container": "#003357",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#ffb693",
        "on-primary-fixed": "#351000",
        "on-primary-fixed-variant": "#7a3000",
        "secondary-fixed": "#9cf5c0",
        "secondary-fixed-dim": "#80d8a5",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005231",
        "tertiary-fixed": "#d0e4ff",
        "tertiary-fixed-dim": "#9ccaff",
        "on-tertiary-fixed": "#001d35",
        "on-tertiary-fixed-variant": "#00497b",
        background: "#fff8f6",
        "on-background": "#261812",
        "surface-variant": "#f8ddd2",
        "map-background": "#0B0B0C",
        "map-surface": "#161618",
        "map-on-surface": "#E5E2E3",
        "map-outline": "#28282A",
        "map-chili": "#FF3B30",
        "map-mango": "#FFB020",
        "map-lime": "#C8F542",
        "map-glow": "#FFB4AA",
        "sheet-background": "#F8FAFC",
        "sheet-surface": "#FFFFFF",
        "sheet-surface-low": "#F2F4F6",
        "sheet-on-surface": "#191C1E",
        "sheet-on-surface-muted": "#5A6570",
        "sheet-outline": "rgba(25, 28, 30, 0.08)",
        "tertiary-dark": "#233148",
      },
      fontFamily: {
        "display-map": ["var(--font-anton)"],
        "map-pin": ["var(--font-dm-sans)"],
        "title-md": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-be-vietnam-pro)"],
        "label-caps": ["var(--font-be-vietnam-pro)"],
        "headline-sheet": ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "display-map": ["48px", { lineHeight: "1.1", fontWeight: "400" }],
        "map-pin": ["11px", { lineHeight: "12px", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-sheet": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "sheet-padding": "24px",
      },
    },
  },
};

export default config;
